config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'home#index'

  resources :users
  resources :products
  resources :emprestimo
  resources :sessions, only: [:new, :create, :destroy]

  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#create', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'emprestar', to: 'products#new', as: 'emprestar'
  get 'empresta', to: 'products#index', as: 'empresta'
  get 'empresta_produto', to: 'emprestimo#create', as: 'empresta_produto'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emprestimo.rb
class Emprestimo < ApplicationRecord
  has_one :user, :class_name => "user"
  has_one :product, :class_name => "product"
end

app/models/lend.rb
class Lend < ApplicationRecord
  has_one :user, :class_name => "user"
  has_one :product, :class_name => "product"
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
  
end

app/controllers/emprestimo_controller.rb
class EmprestimoController < ApplicationController
    before_action :set_product, :set_user

    def create
      @user, @product = Emprestimo.new(user_params, product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to @product, notice: 'Emprestimo was successfully created.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :url, :description)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :url, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = "Email ou senha invalidos!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emprestimo_helper.rb
module EmprestimoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<head>
<link rel="stylesheet" href="../../stylesheets/home.scss">
</head>
<!-- style="background-color: #f56f0f -->
<body>
<header class="navbar navbar-fixed-top navbar-inverse navbar-dark bg-primary">
	<div class="navbar-inner">
		<div class="container">
			<nav class="barra-nav">
				<p class="titulo">Empresta UFSCar</p>
				<% if current_user %>
					<%= link_to "Emprestar", empresta_path %>
					<%= link_to "Preciso disso",  emprestar_path %>
					<%= link_to "O que emprestei", logout_path %>
					<ul class="pull-right">
						Logged in as <%= current_user.email %>.
						<%= link_to "Log Out", logout_path %>
					</ul>
				<% else %>

				<ul class="pull-right">
					<%= link_to "Sign Up", signup_path %> or
					<%= link_to "Log In", login_path %>
				</ul>
				<% end %>
			</nav>
		</div>
	</div>
</header>

<div class="conteudo">
	<img class="imagem" src="https://www.cpp.org.br/media/k2/items/cache/b4e8bec3ce7a0815b1c19d3fb5388312_XL.jpg">
	<p id=”notice”><%= notice %></p>

	<span class="texto">
		<h1 style="font-size: 100px; text-align: center; color: white;">Empresta UFSCar</h1>
		<p style="font-size: 40px; color: white;">Faça login ou crie sua conta para emprestar itens!</p>
	</span>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emprestaufscar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<!DOCTYPE html>
<head>
<link rel="stylesheet" href="../../stylesheets/home.scss">
<link rel="stylesheet" href="app/assets/stylesheets/users.scss" />
</head>
<!-- style="background-color: #f56f0f -->
<body>
<header class="navbar navbar-fixed-top navbar-inverse navbar-dark bg-primary">
	<div class="navbar-inner">
		<div class="container">
			<nav class="barra-nav">

        <p class="titulo">Empresta UFSCar</p>
				<%= link_to "Emprestar", empresta_path %>
				<%= link_to "Preciso disso",  emprestar_path %>
				<%= link_to "O que emprestei", logout_path %>
				<ul class="pull-right">
					<% if current_user %>
						Logged in as <%= current_user.email %>.
					<%= link_to "Log Out", logout_path %>
					<% else %>
						<%= link_to "Sign Up", signup_path %> or
						<%= link_to "Log In", login_path %>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header> 
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="login-page">
      <div class="form">
        <form>
        <div class="arrow_left">
          <%= link_to image_tag("left-arrow.png", size: "16x16",class: "arrow_left") ,products_path %>
        </div>
          <div class="form-group">
          <label>Nome</label>
            <%= form.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
          
          <label>Url</label>
            <%= form.text_field :url, type: "file", accept:"image/x-png,image/gif,image/jpeg" %>
          </div>
          <div class="form-group">
            <label>Descrição</label>
            <textarea rows="3"
              <%= form.text_field :description, class: 'form-control' %>
            </textarea>
          </div>     
          <div class="actions">
          <%= form.submit 'Criar Produto', class: 'btn btn-primary' %>
        </div>     
        </form>
      </div>
    </div>
  <% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/products.scss" /> 

<header class="navbar navbar-fixed-top navbar-inverse navbar-dark bg-primary">
    <div class="navbar-inner">
        <div class="container">
            <nav class="barra-nav">

                <p class="titulo">Empresta UFSCar</p>
                <%= link_to "Emprestar", empresta_path %>
                <%= link_to "Preciso disso",  emprestar_path %>
                <%= link_to "O que emprestei", logout_path %>
                <ul class="pull-right">
                    <% if current_user %>
                        Logged in as <%= current_user.email %>.
                    <%= link_to "Log Out", logout_path %>
                    <% else %>
                        <%= link_to "Sign Up", signup_path %> or
                        <%= link_to "Log In", login_path %>
                    <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header> 

<br>
<br>
<br>

<h1 style="text-align: center;">Produtos</h1>
    
<div id="main">

    <% @products.each do |product| %>

    <div class="container-card">
        <div class="card" style="width: 18rem;">
            <%= link_to image_tag("ufszinha.jpg", size: "165x120")  %>
            <div class="card-body" style="margin-left: 10px; margin-right: 10px;">
                <h3 class="card-title" style="text-align: center;"> <%= product.name %> </h3>
            </div>
        </div>

        <div class="card-descricao">
            <p class="card-text"> <%= product.description %> </p>
        </div>

        <div style="float: right; margin: auto; margin-left: 20px;"> <%= button_to 'Emprestar',empresta_produto_path,  method: :get, data: { user: current_user, product: product.id } %> </div>

    </div>

    <% end %>

</div>
<br> <br><br>
<div align="center"> <button> <%= link_to 'Novo produto', new_product_path %> </button> </div>

app/views/products/new.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/users.scss" />
<div class="title">
    <h1>Novo Produto</h1>
</div>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @product.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<!DOCTYPE html>
<head>
<link rel="stylesheet" href="../../stylesheets/home.scss">
<link rel="stylesheet" href="app/assets/stylesheets/users.scss" />
</head>
<!-- style="background-color: #f56f0f -->
<body>
<header class="navbar navbar-fixed-top navbar-inverse navbar-dark bg-primary">
	<div class="navbar-inner">
		<div class="container">
			<nav class="barra-nav">

				<p class="titulo">Empresta UFSCar</p>
				<%= link_to "Emprestar", empresta_path %>
				<%= link_to "Preciso disso",  emprestar_path %>
				<%= link_to "O que emprestei", logout_path %>
				<ul class="pull-right">
					<% if current_user %>
						Logged in as <%= current_user.email %>.
					<%= link_to "Log Out", logout_path %>
					<% else %>
						<%= link_to "Sign Up", signup_path %> or
						<%= link_to "Log In", login_path %>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header> 
<%= form_with(model: user, local: true) do |form| %>
  <div class="login-page">
    <div class="form">
      <form>
        <%= link_to image_tag("left-arrow.png", size: "16x16",class: "arrow_left"),root_path %>
        <div class="form-group">
        <label for="exampleInputPassword1">E-mail</label>
          <%= form.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
        <label for="exampleInputPassword1">Senha</label>
          <%= form.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Confirmar Senha</label>
          <%= form.password_field :password , class: 'form-control'  %>
        </div>
        <%= form.submit 'Cadastre-se', class: 'btn btn-primary' %>
      </form>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/users.scss" />
<div class="title">
    <h1>Novo Usuário</h1>
</div>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="show-email">
<p id="id-email">
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p id="id-email2">Cadastro realizado com sucesso!</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>